### ISSUE TITLE
Crash w/ Conditional Mob Spawning

### ISSUE THREAD

**Issue by WenXin20** [TelepathicGrunt/WorldBlender#10]
`Minecraft v1.15.2`
`Forge v31.2.31`
`World Blender v1.3.6`
`Nature Plus`: https://github.com/WenXin20/natureplus 
[natureplus-1.15.2-1.9.2.jar.zip](https://github.com/TelepathicGrunt/WorldBlender/files/4997451/natureplus-1.15.2-1.9.2.jar.zip)

MCreator recently added something called conditional mob spawning, which allows the creator to create a procedure that allows mobs to spawn only in certain conditions. After making these changes, my server crashes with World Blender and Nature Plus.
Blacklisting the entire mod in the config fixes the crash for the time being.
[Latest.log](https://gist.github.com/WenXin20/67580db2b69ad0d584ea06fdd611f7ab)
[Crash Report](https://gist.github.com/WenXin20/5352e2996186167e4c33e063d4fbd4c7)

**Comment by TelepathicGrunt** [comment]
Oh no. Mcreator.... I'm scared at what horrors lies in wait for me from its codebase!

**Comment by TelepathicGrunt** [comment]
I think I know the issue but I'll need you to test with this jar. If it crashes still, please tell me as then I'll know for certain that Mcreator is not registering entities which is MASSIVELY concerning on their part and for the love of all mods everywher, I really hope that isn't the case lmao

[world_blender-1.15.2-1.3.8-beta.zip](https://github.com/TelepathicGrunt/WorldBlender/files/4997837/world_blender-1.15.2-1.3.8-beta.zip)

**Comment by WenXin20** [comment]
Oh boy, that would be bad, but I'm pretty sure they are being registered in their own package for each entity, and the mod worked with World Blender in the previous MCreator snapshot. 
But thanks, I'll give it a try later.

**Comment by WenXin20** [comment]
Hello, sorry it took a while. The beta version you provided does not crash the server anymore. Thanks!

**Comment by TelepathicGrunt** [comment]
Oh thank you! I'm glad you commented as I completely forgot about this lol. I believe the issue was that I was getting the ID of the entity through a special method that Forge patched into the entities. mcreator does not have this patch so their entities would return nothing for the ID when I used that one method.

I, now, instead get the ID straight from the registry so the ID always exists.

v1.3.7 will be released on curseforge with the fix. Thank you for reporting this!

**Comment by WenXin20** [comment]
Thanks!
