### ISSUE TITLE
ignore null entries in surfacebuilder configs from other mods

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/WorldBlender#13]
byg crash
https://github.com/TelepathicGrunt/WorldBlender/blob/be816582d62f6b5d3967f9c80a25034b632b390c/src/main/java/com/telepathicgrunt/world_blender/the_blender/TheBlender.java#L459

**Comment by CorgiTaco** [comment]
Better catch the nulls >:)

**Comment by TelepathicGrunt** [comment]
fixed in 2.0.3
