### ISSUE TITLE
Array Index out of Bounds Error

### ISSUE THREAD

**Issue by DatrixTHLK** [TelepathicGrunt/WorldBlender#15]
Hi there,

 I've gotten this error when I had your mod within my mod list. I can only guess this means that Out of bounds means it has gone beyond whatever it has gone beyond(???) for lack of better terms. Can you help explain what this means if I haven't done it correctly?

Minecraft: 1.16.3
Forge: 34.1.25
World Blender: 2.0.4

Crash report: https://gist.github.com/DatrixTHLK/a6d24883aee9c8045b2bec06a6aa5715

**Comment by TelepathicGrunt** [comment]
Oh no! A rendering issue! uhhh

Can you show me your latest.log file? It will be in the logs folder above your mods folder. It will have more info as to what happened. And what other mods do you have on?

And what exactly what happening when this crash occurred? Sorry for all the questions but the more info, the easier it will be to find the source of the issue.

**Comment by DatrixTHLK** [comment]
Strange...it works just fine now.

When I went into my saved world it froze up and went to an exit code zero. Working with a completely new game file though. So I guess I'll have to give up my old world and work with the new world now.

**Comment by TelepathicGrunt** [comment]
If you can trigger the world freezing up again and then give me the latest.log file, it'll say why the exit code zero occurred. I cant do anything without any info

**Comment by DatrixTHLK** [comment]
FML Log: https://gist.github.com/DatrixTHLK/aaa0d7800d202e11bc3062ba7f4e0bd8

I hope this can help.

**Comment by DatrixTHLK** [comment]
I noticed you updated the mod so I'll try it with that version and see what happens

**Comment by TelepathicGrunt** [comment]
Few things, are you using All The Mods 6 modpack? If so, what additional mods do you have on or can you export your mods so I can test?

Also, are you using the latest Blame mod version? 1.4.6 is released but the log looks like it is an older version I think. I should have blame put it's version in the logs so i can tell when people are outdated

**Comment by DatrixTHLK** [comment]
I'm not using any modpacks. I simply download the mods from Curseforge and then play around with them experiencing the game uninhibited eventually running into issues. I'll restart my computer and see if that fixes the issue first...I'll contact you with whatever problem happens with the game.

I would love it if a mod could tell me what mods need updating.

**Comment by DatrixTHLK** [comment]
Here is the mod list. I took out some that weren't need because they were redundant: https://filebin.net/ckd17chf4ovev2bu

Blame is up to date at 1.4.6 atm

Latest FML Report: https://gist.github.com/DatrixTHLK/39aff47c870c3512339b52ad6246ba47

**Comment by TelepathicGrunt** [comment]
Sorry. Just wanted to let you know that I still havent forgotten about this. Forge released a breaking change that broke all my mods. Once my mods are updated to work on newest forge, I can revisit this bug and figure out what the heck is going on lol

**Comment by DatrixTHLK** [comment]
Thanks for getting back with me on this. I appreciate that! I don't expect a miracle right now. Just take your time on this, and don't rush.

**Comment by TelepathicGrunt** [comment]
Just tested and flew around in my dimension. Even exited and re-entered and couldn't get this crash to occur. Has the crash happen again for your no? If not, it may just been a one time crash with another mod for some weird reason

**Comment by DatrixTHLK** [comment]
Exit 0 means a successful exit. However, what would have caused the "successful exit" error...I haven't a clue. I'm going to try it again to make sure it works

**Comment by TelepathicGrunt** [comment]
Any news? if the crash hasnt happened again, I'll close this issue then.  Strange tho

**Comment by DatrixTHLK** [comment]
Unfortunately, I haven't been playing or testing minecraft lately with mods in general. I know that all the mods I use for 1.16.4 are updated. I just haven't been able to play with them yet. I will give it a try before today is over with and let you know. 

Edit: I'm just now trying to get into the game. It works for now I haven't had any exit code zeros as of yet or any crashes. Thanks for updating the mod and the response. I appreciate it!
