### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by Shadows-of-Fire** [TelepathicGrunt/WorldBlender#2]
Hi, this error isn't really your fault, but you should probably catch it and assign blame to whatever is causing it: https://gist.github.com/Shadows-of-Fire/7c83dd262cec9f2f77a8839d0113a501

It would appear to be the fault of something not registering a feature, and granted, there's not really anything that even requires that features be registered to begin with, so this crash might become more common (I had at least two mods in my environment causing it).

**Comment by TelepathicGrunt** [comment]
Thank you for reporting this issue! It's actually more of an issue on my end as I forgot to do some null checking. I just released v.1.2.4 to fix this issue and you can download it from CurseForge. <https://www.curseforge.com/minecraft/mc-mods/worldblender>

Again, thank you for letting me know! :)
