### ISSUE TITLE
Incompatibility crash with Cyclops

### ISSUE THREAD

**Issue by sciguyryan** [TelepathicGrunt/WorldBlender#31]
Hi!

While putting together a (fairly large) 1.16 modpack I came upon a crash while attempting to create a new world. An example crash report has been attached here. This crash is completely repeatable as long as World Blender is enabled in the pack.

I have tried to narrow down what conflict could be causing this, but with no luck so far. I checked to see if the Java version was the issue, turned out not to be the case.

Controllable, Random Patches, Shut Up Experimental Settings, Immersive Engineering, KubeJS and Botania are mentioned in the crash log. Unfortunately even with all of those disabled the crash still persists.

I am unsure where else to look here without disabling blocks of mods to see if I can narrow it down. I will do so if it will be of any help.

[crash-2021-01-25_14.11.33-client.txt](https://github.com/TelepathicGrunt/WorldBlender/files/5867187/crash-2021-01-25_14.11.33-client.txt)

**Comment by TelepathicGrunt** [comment]
Someone's configuredfeature (stuff like trees, ores, etc) is broken and cannot be converted to JSON which World Blender does to compare features. Do you have any mcreator mods on? If so, what mcreator mods are you using? 

If you cant find out, I can make an experimental jar later to try and print out the name of the crashing configuredfeature which would help narrow down the mod quickly.

**Comment by TelepathicGrunt** [comment]
can you remove world blender and add on Blame https://www.curseforge.com/minecraft/mc-mods/blame

then launch the world and then give me the latest.log file? Blame has code to find the broken configuredfeature which should help us

**Comment by sciguyryan** [comment]
I have disabled world blender and created a new world with the pack. It worked fine without it installed. Please find the file attached as requested.

I did have a quick look but I have no idea what I am looking for. I haven't used Minecraft for some time, I'm getting back into it after a very long period of absence.

[latest.log](https://github.com/TelepathicGrunt/WorldBlender/files/5872923/latest.log)

**Comment by TelepathicGrunt** [comment]
Blame made a report towards the bottom that stated the broken configuredfeatures or unregistered ones. Looks like cyclops's configuredfeatures are broken and cannot be turned into json properly. I will reach out to them.

It also says naturesaura and allomancy's configuredfeatures aren't properly registered. Though what version of naturesaura are you using? I thought they fixed their configuredfeatures in their latest update. I can go talk to those two mods to help them out. 

but right now, World Blender is crashing due to cyclops. You'll have to leave off either World Blender or Cyclops until their configuredfeature is fixed

**Comment by sciguyryan** [comment]
Nature's Aura is at version 33.4. I have just checked and this is the latest version available on CurseForge.

As for Allomancy, that would be the following mod:

https://www.curseforge.com/minecraft/mc-mods/allomancy

Thanks for looking into this for me. If there is anything I can do to assist here, please do let me know.

**Comment by TelepathicGrunt** [comment]
I just notified Allomancy so they should work on a fix soon. As for nature, weird but I'll contact them.

the hard part is cyclops is actually a library mod so some other mod is using cyclops and is registering a broken configuredfeature through them. Can you find out and let me know what mod is depending on cyclops? It would help greatly!

**Comment by TelepathicGrunt** [comment]
Nevermind. The cyclops dev found and told me the mod. It appears to be IntegratedDynamics. Hopefully this can be resolved soon!
https://github.com/CyclopsMC/IntegratedDynamics/issues/975

**Comment by sciguyryan** [comment]
I have updated to the latest ID version and the startup crash has been fixed. I am happy to close this now and open a new bug should any of the other two mods cause issues here.

Thanks for helping resolve this!
