### ISSUE TITLE
Mobs go invisible when using minimap/worldmap or running/teleporting

### ISSUE THREAD

**Issue by Mewcenary** [TelepathicGrunt/WorldBlender#41]
I am playing the Minecraft mod, Ice and Fire Magic Modpack.  I've updated the Minimap to 21.10.0.1 for Forge and the World Map to 1.14.1 for Forge 1.16.5.

When I run using the minimap with the tab button pressed to see mobs, they end up going invisible and I can't see them on any map or standing in front of them.  Nothing shows, only their sound works.  This happens to all mob types; hostile, friendly, etc.  Along with them being invisible, oddly chests and beds, and any blocks you break are invisible as well.

I've changed my settings, updated other mods, restarted, reinstalled the maps and CurseForge, and the bug is still there.  I am not sure what the conflict is.  As you can see in the pictures, the villagers, animals, mobs, chests, are invisible.  I can kill, or use items, I just can't see them.
@TelepathicGrunt 
RAM allocated for Minecraft:  4GB
Java:  (build 1.8.0_291-b10)

Device name	xxxxxxxxx
Processor	Intel(R) Core(TM) i3-2125 CPU @ 3.30GHz   3.30 GHz
Installed RAM	8.00 GB (7.90 GB usable)
Device ID	        3B51426A-336E-444A-BB82-DEA98B2745F8
Product ID	00330-75059-10411-AAOEM
System type	64-bit operating system, x64-based processor
Edition	        Windows 10 Pro
Version	        20H2
Installed on	‎7/‎20/‎2020
OS build	        19042.985
Experience	Windows Feature Experience Pack 120.2212.2020.0

![image](https://user-images.githubusercontent.com/85654348/121449036-cd5cae00-c94d-11eb-8382-1c77cc11f936.png)
![image](https://user-images.githubusercontent.com/85654348/121449079-e5ccc880-c94d-11eb-925d-47de5b917bf4.png)
![image](https://user-images.githubusercontent.com/85654348/121449401-9b981700-c94e-11eb-93ba-e1f2a2312566.png)
![image](https://user-images.githubusercontent.com/85654348/121449517-d601b400-c94e-11eb-80fa-34bca018a925.png)
![image](https://user-images.githubusercontent.com/85654348/121449569-edd93800-c94e-11eb-9fac-f6144d2c5dc5.png)
![image](https://user-images.githubusercontent.com/85654348/121449618-05182580-c94f-11eb-88a5-68392158b0d4.png)
![image](https://user-images.githubusercontent.com/85654348/121449689-26791180-c94f-11eb-9741-6e75a9b225c9.png)
![image](https://user-images.githubusercontent.com/85654348/121449734-3ee92c00-c94f-11eb-9b08-39bb40e59dd6.png)

**Comment by TelepathicGrunt** [comment]
Oof I somehow missed this issue report. However, World Blender should not conflict at all with minimap mods or mob rendering at all. In fact, the only rendering I even do is for my portal block which you do not have on screen. Are you sure the conflict is actually with my mod and not something else? Were you able to resolve the issue by now?

**Comment by Mewcenary** [comment]
> Oof I somehow missed this issue report. However, World Blender should not conflict at all with minimap mods or mob rendering at all. In fact, the only rendering I even do is for my portal block which you do not have on screen. Are you sure the conflict is actually with my mod and not something else? Were you able to resolve the issue by now?

Yeah, it only happened when I used the minimap while running. But I believe the issue is resolved now, another person who works with you? Helped me resolve it by updating to your newer mod version.  Thank you for your response regardless XD I LOVE your mod it's fantastic!!!. I will close this now :3
