### ISSUE TITLE
crash creating new world

### ISSUE THREAD

**Issue by JadeFalcon** [TelepathicGrunt/WorldBlender#44]
[crash-2021-09-05_13.23.42-client.txt](https://github.com/TelepathicGrunt/WorldBlender/files/7112315/crash-2021-09-05_13.23.42-client.txt)
[latest.log](https://github.com/TelepathicGrunt/WorldBlender/files/7112316/latest.log)

**Comment by TelepathicGrunt** [comment]
I never seen this crash before. Something has a field State but it isnt a json object. I'll try and harden the mod against these kinds of assumptions. Would you be able to provide me the exported modpack profile so I can try and test it on my end?

**Comment by TelepathicGrunt** [comment]
You can give this test jar a try (be sure to unzip this folder to get the jar). See if that fixes the crash
[world_blender-1.16.5-4.0.1b-forge.zip](https://github.com/TelepathicGrunt/WorldBlender/files/7112505/world_blender-1.16.5-4.0.1b-forge.zip)

**Comment by JadeFalcon** [comment]
That did fix the crash, I also narrowed down the crash to the newest version of Mystical World/Mystical Biomes

**Comment by TelepathicGrunt** [comment]
thank you! The fix is now released on curseforge.
