### ISSUE TITLE
1.15.2-1.3.3 NoSuchMethodError on Server when players place portal blocks

### ISSUE THREAD

**Issue by kreezxil** [TelepathicGrunt/WorldBlender#7]
Issue:  1.15.2-1.3.3 crashes dedicated server Forge 1.15.2 build 31.1.46

Notes:
     

crash report: 
http://paste.ubuntu.com/p/cjt7VZ9rzK/

fml server latest: 
http://paste.ubuntu.com/p/MPP7PdpsSP/

**Comment by TelepathicGrunt** [comment]
Thank you for letting me know! v1.3.4 is now out and should fix this bug.
<https://www.curseforge.com/minecraft/mc-mods/worldblender/files>

I'll close this issue now. Let me know if there any another problems!
