### ISSUE TITLE
Crash w/ The Conjurer Mod and Others

### ISSUE THREAD

**Issue by WenXin20** [TelepathicGrunt/WorldBlender#8]
`Minecraft v1.15.2`
`Forge v31.2.5`
[`The Conjurer v1.0.2`](https://www.curseforge.com/minecraft/mc-mods/the-conjurer)
[`Structure Gel API v1.0.0`](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)

I got a crash after trying to a world using the World Blender type. The crash report invovles both Conjurer Illager and it's required mod, Structure Gel.
[Crash Report](https://gist.github.com/WenXin20/7035fdaf7a429e344a7813209a1a8275)

(The mod also crashes or errors with Dimensional Dungeons, Resourceful Bees, and the Lord of the Rings mod, download found [here](https://lotrminecraftmod.fandom.com/wiki/Updates/Renewed), under snapshot 1.2, but had not saved the logs as no crash reports saved. 
I will create seperate issues once I can get those logs, but for now I have blacklisted these mods in the config.)

**Comment by TelepathicGrunt** [comment]
Looking at this specific log, it seems The Conjurer messed up their structure placement code. I can make a bug report to them to let them know to make sure they always are giving their random number generator a positive number in their structure. The bug must be more easily triggered by world blender's terrain or something. Hopefully they are open source so I can see exactly what they did. 

brb lol

**Comment by TelepathicGrunt** [comment]
Alright, I opened up an issue report on their page so hopefully they can fix the crash soon! :)
https://gitlab.com/modding-legacy/the-conjurer/-/issues/2

I'll close this issue when their crash is fixed

**Comment by WenXin20** [comment]
Thanks!

**Comment by TelepathicGrunt** [comment]
Oof I forgot to close this issue lol.  Conjurer fixed this issue a few days ago so I’ll close the report now
